name: Pyinstaller for linux

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: |
        pip install pyinstaller==5.3
    - uses: actions/checkout@v3
    - run: |
        pyinstaller main.spec
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/lsp-server-wrapper
