name: Pyinstaller for linux

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: |
        pip install pyinstaller==5.3
    - uses: actions/checkout@v3
    - run: |
        pyinstaller main.spec
    - uses: actions/upload-artifact@v3
      with:
        name: lsp-server-wrapper
        path: dist/lsp-server-wrapper
